#!/usr/bin/env zsh

ignore_files=(
  Go.gitignore
  Global/macOS.gitignore
  Global/Linux.gitignore
  Node.gitignore
  Global/VisualStudioCode.gitignore
)

DOTFILES=${DOTFILES:-..}

cat > $DOTFILES/git/gitignore.symlink <<EOF
# Generated by gitignore.generate.sh
# ----------------------------------

EOF

for ignore_file in $ignore_files
do

cat >> $DOTFILES/git/gitignore.symlink <<EOF

# --- $ignore_file ---

EOF

curl -sSL https://github.com/github/gitignore/raw/main/$ignore_file >> $DOTFILES/git/gitignore.symlink

done

cat >> $DOTFILES/git/gitignore.symlink <<EOF

# --- Other ---

.envrc
tmp/
temp/
EOF
